#' The application server-side
#'
#' @param input,output,session Internal parameters for {shiny}.
#'     DO NOT REMOVE.
#'
#' @keywords internal
#' @noRd
app_server <- function(input, output, session) {
  sktb_module("sktb-app")
}

#' @keywords internal
#' @noRd
sktb_module <- function(id) {
  shiny::moduleServer(
    id,
    function(input, output, session) {
      renew_ojichat <-
        shiny::eventReactive(input$render, {
          message <-
            sktb_sample_message(1L) %>%
            sktb_conv_tags_all(input$name, input$emoji) %>%
            sktb_insert_comma(input$pos, input$comma)
          message
        })
      output$plot <- shiny::renderPlot(
        {
          renew_ojichat() %>%
            sktb_plot_ojichat()
        },
        alt = "Meme generated by {shaketoba} R package; Enjoy\U0001f973",
        execOnResize = FALSE
      )
    }
  )
}

#' Plot an ojichat meme
#'
#' @param str ojichat message.
#' @param img passed to \code{meme::meme()}.
#' @return object returned from \code{meme::meme}.
#'
#' @export
sktb_plot_ojichat <- function(str, img = NULL) {
  s <- stringi::stri_replace_all_fixed(str, " ", "\n")
  if (is.null(img)) img <- app_sys(dqrng::dqsample(sktb_images(), 1))
  meme::meme(
    img,
    s,
    "",
    size = 1.4,
    color = "snow",
    font = "SetoFont",
    vjust = 0.4,
    bgcolor = "violet"
  )
}
